/** Welcome lines (100) — Portuguese, German, Dutch, Russian. Same order as WELCOME_EN. */

export const WELCOME_PT: string[] = [
  'Brrr! Consegues pensar sem gelar?',
  'Sou calmo… mas rápido!',
  'Brilha forte, pensa mais forte!',
  'Move-te depressa… responde mais depressa!',
  'Flui como eu e vences!',
  'Sou duro… mas justo!',
  'Doce por fora, truques por dentro!',
  'Roda até acertares!',
  'Vamos ver quem responde primeiro!',
  'Cores e números… mistura perfeita!',
  'Segue o ritmo… não falhes!',
  'As perguntas caem… como chuva!',
  'Todos a bordo… o desafio começa!',
  'Suave… mas esperto!',
  'Pequeno mas afiado!',
  'Faz crescer a mente comigo!',
  'Sou rápido como o vento!',
  'Sobe de nível… passo a passo!',
  'Sólido como uma rocha!',
  'Brilha e marca!',
  'Um doce para o cérebro!',
  'Gira, gira… e responde!',
  'Um desafio delicioso!',
  'Mira bem… e acerta!',
  'Ronda perfeita… consegues?',
  'Um desafio crocante!',
  'Escorrega se errares!',
  'Suave… mas não é fácil!',
  'Extra doce, extra difícil!',
  'Arrefece os erros… pensa claro!',
  'A processar… consegues acompanhar?',
  'Sistema pronto a jogar!',
  'Faz rodar a mente!',
  'Liga ideias depressa!',
  'Pequeno mas veloz!',
  'Acende o teu brilho!',
  'Pergunta mistério!',
  'Toca… e acerta!',
  'Estica a mente!',
  'Protege as respostas!',
  'Brilha em cada resposta!',
  'Nada depressa… pensa melhor!',
  'Grande desafio à frente!',
  'Pop! Responde já!',
  'De lado… mas firme!',
  'Vai com a corrente!',
  'Não te enredes!',
  'Nada até à resposta!',
  'Tenho imensas opções!',
  'Rápido… mesmo rápido!',
  'Tudo gira… mantém-te atento!',
  'Calma e precisão!',
  'Desafio de outro nível!',
  'Passo ligeiro!',
  'Mira alto!',
  'Brilha no escuro!',
  'Os desafios chovem!',
  'Isto é de outro mundo!',
  'Gira… e responde!',
  'Aqui tudo pode acontecer!',
  'Encontra a saída!',
  'Cada floco conta!',
  'Cresce a cada acerto!',
  'Sente o ritmo!',
  'Apertável… mas difícil!',
  'Aumenta o calor!',
  'Cria a resposta!',
  'Hora de aprender!',
  'Receita perfeita!',
  'Cura esses erros!',
  'Alto e rápido!',
  'Carrega no certo!',
  'Velocidade máxima!',
  'Está tudo ligado!',
  'Modo jogo: LIGADO!',
  'Constrói a resposta!',
  'Próxima paragem: certo!',
  'Salta e responde!',
  'Junta as ideias!',
  'Flutua… e pensa!',
  'Um desafio mágico!',
  'Um pouco de magia!',
  'Um desafio lendário!',
  'Luz e lógica!',
  'Acredita em ti!',
  'Não te percas!',
  'Enfrenta o desafio!',
  'Claridade total!',
  'Sente o desafio!',
  'Tudo é possível!',
  'Mente calma, respostas certas!',
  'Corre e marca!',
  'Mergulha!',
  'Esmaga esse recorde!',
  'Surfa na onda e responde!',
  'Sobe esse nível!',
  'Não pares!',
  'Impulsiona o cérebro!',
  'Salta alto!',
  'Um nocaute… de inteligência!',
];

export const WELCOME_DE: string[] = [
  'Brrr! Kannst du klar denken ohne einzufrieren?',
  'Ich bin ganz ruhig… aber schnell!',
  'Strahl hell, denk heller!',
  'Beweg dich schnell… antworte schneller!',
  'Fließ wie ich und du gewinnst!',
  'Ich bin hart… aber fair!',
  'Süß außen, schlau innen!',
  'Dreh es rund… bis es passt!',
  'Mal sehen, wer zuerst antwortet!',
  'Farben und Zahlen… perfekte Mischung!',
  'Halte den Takt… verfehle nicht!',
  'Fragen fallen… wie Regen!',
  'Alle an Bord… jetzt geht’s los!',
  'Weich… aber heimtückisch!',
  'Klein aber schlau!',
  'Lass deinen Geist mit mir wachsen!',
  'Ich bin schnell wie der Wind!',
  'Level hoch… Schritt für Schritt!',
  'Fest wie ein Fels!',
  'Strahle und punkte!',
  'Ein süßer Kick fürs Gehirn!',
  'Dreh dich, dreh dich… und antworte!',
  'Eine köstliche Herausforderung!',
  'Ziele gut… und triff!',
  'Perfekte Runde… schaffst du das?',
  'Eine knackige Challenge!',
  'Ausrutschen wenn du stolperst!',
  'Weich… aber nicht leicht!',
  'Extra süß, extra hart!',
  'Kühl die Fehler ab… denk klar!',
  'Verarbeitung… kannst du mithalten?',
  'System bereit zum Spielen!',
  'Roll den Kopf an!',
  'Verknüpfe Ideen schnell!',
  'Klein aber flott!',
  'Mach dein Licht an!',
  'Geheimnisfrage!',
  'Tippen… und treffen!',
  'Dehn deinen Kopf!',
  'Bewahre deine Antworten!',
  'Strahle bei jeder Antwort!',
  'Schwimm schnell… denk klüger!',
  'Riesige Herausforderung voraus!',
  'Pop! Jetzt antworten!',
  'Seitlich… aber sicher!',
  'Schwimm mit der Strömung!',
  'Verwickle dich nicht!',
  'Schwimm zur Antwort!',
  'Ich habe viele Optionen!',
  'Schnell… wirklich schnell!',
  'Alles dreht sich… bleib wachsam!',
  'Ruhig und genau!',
  'Weltraum-Level!',
  'Schneller Schritt!',
  'Ziele hoch!',
  'Strahle in der Dunkelheit!',
  'Die Herausforderungen fallen!',
  'Das ist nicht von dieser Welt!',
  'Dreh dich… und antworte!',
  'Hier ist alles möglich!',
  'Finde den Weg hinaus!',
  'Jede Flock zählt!',
  'Wachse mit jeder richtigen Antwort!',
  'Spür den Beat!',
  'Zum Knuddeln… aber hart!',
  'Dreh die Hitze auf!',
  'Erschaffe die Antwort!',
  'Zeit zu lernen!',
  'Perfektes Rezept!',
  'Heil diese Fehler!',
  'Hoch und schnell!',
  'Drück die richtige!',
  'Maximale Geschwindigkeit!',
  'Alles ist verbunden!',
  'Spielmodus: AN!',
  'Baue die Antwort!',
  'Nächster Halt: richtig!',
  'Spring und antworte!',
  'Schnapp die Ideen zusammen!',
  'Schweb… und denk!',
  'Eine magische Herausforderung!',
  'Ein bisschen Magie!',
  'Eine legendäre Herausforderung!',
  'Licht und Logik!',
  'Glaub an dich!',
  'Verlauf dich nicht!',
  'Steh die Challenge durch!',
  'Kristallklar!',
  'Spür die Herausforderung!',
  'Alles ist möglich!',
  'Ruhiger Kopf, klare Antworten!',
  'Lauf und triff!',
  'Tauche ein!',
  'Knack den Rekord!',
  'Reit die Welle und antworte!',
  'Erklimm das Level!',
  'Hör nicht auf!',
  'Boost dein Gehirn!',
  'Spring hoch!',
  'Ein Knockout… fürs Köpfchen!',
];

export const WELCOME_NL: string[] = [
  'Brrr! Kun je nadenken zonder te bevriezen?',
  'Ik ben kalm… maar snel!',
  'Straal helder, denk helderder!',
  'Beweeg snel… antwoord sneller!',
  'Stroom als ik en je wint!',
  'Ik ben streng… maar eerlijk!',
  'Lief aan de buitenkant, lastig van binnen!',
  'Draai het rond… tot je het hebt!',
  'Kijken wie het eerst antwoordt!',
  'Kleuren en getallen… perfecte mix!',
  'Houd het ritme… mis niet!',
  'Vragen vallen… als regen!',
  'Stap aan boord… het begint!',
  'Zacht… maar listig!',
  'Klein maar scherp!',
  'Laat je hoofd groeien met mij!',
  'Ik ben zo snel als de wind!',
  'Level omhoog… stap voor stap!',
  'Stevig als een rots!',
  'Straal en scoor!',
  'Een zoete traktatie voor je brein!',
  'Draai, draai… en antwoord!',
  'Een heerlijke uitdaging!',
  'Mik goed… en raak!',
  'Perfecte ronde… lukt het?',
  'Een knapperige uitdaging!',
  'Glibberen als je struikelt!',
  'Zacht… maar niet makkelijk!',
  'Extra zoet, extra taai!',
  'Koel die fouten af… denk helder!',
  'Verwerken… kun je bijbenen?',
  'Systeem klaar om te spelen!',
  'Laat je hoofd rollen!',
  'Koppel ideeën snel!',
  'Klein maar vlot!',
  'Zet je licht aan!',
  'Mysterievraag!',
  'Tik… en raak!',
  'Rek je geest!',
  'Bescherm je antwoorden!',
  'Straal bij elk antwoord!',
  'Zwem snel… denk slimmer!',
  'Grote uitdaging voor je!',
  'Pop! Antwoord nu!',
  'Schuin… maar stabiel!',
  'Ga mee met de stroom!',
  'Raak niet in de knoop!',
  'Zwem naar het antwoord!',
  'Ik heb genoeg opties!',
  'Snel… heel snel!',
  'Alles draait… blijf scherp!',
  'Rustig en precies!',
  'Ruimte-level uitdaging!',
  'Snelle stap!',
  'Mik hoog!',
  'Straal in het donker!',
  'Uitdagingen vallen!',
  'Dit is uit een andere wereld!',
  'Draai… en antwoord!',
  'Hier mag alles!',
  'Vind de uitweg!',
  'Elke vlok telt!',
  'Groei met elk goed antwoord!',
  'Voel de beat!',
  'Knuffelbaar… maar lastig!',
  'Zet de hitte hoger!',
  'Maak het antwoord!',
  'Tijd om te leren!',
  'Perfect recept!',
  'Genees die fouten!',
  'Hoog en snel!',
  'Druk de juiste!',
  'Maximale snelheid!',
  'Alles is verbonden!',
  'Spelmodus: AAN!',
  'Bouw het antwoord!',
  'Volgende stop: goed!',
  'Stuit en antwoord!',
  'Klik de ideeën in elkaar!',
  'Zweef… en denk!',
  'Een magische uitdaging!',
  'Een beetje magie!',
  'Een legendarische uitdaging!',
  'Licht en logica!',
  'Geloof in jezelf!',
  'Raak niet verdwaald!',
  'Sta de uitdaging door!',
  'Kristalhelder!',
  'Voel de uitdaging!',
  'Alles is mogelijk!',
  'Rustige geest, duidelijke antwoorden!',
  'Ren en scoor!',
  'Duik erin!',
  'Sla dat record kapot!',
  'Surf op de golf en antwoord!',
  'Beklim dat level!',
  'Stop niet!',
  'Boost je brein!',
  'Spring hoog!',
  'Een knock-out… voor je slimme kop!',
];

export const WELCOME_RU: string[] = [
  'Брр! Сможешь думать, не застыв?',
  'Я спокоен… но быстр!',
  'Свети ярче — думай яснее!',
  'Двигайся быстрее… отвечай ещё быстрее!',
  'Текли как я — и победишь!',
  'Я суров… но честен!',
  'Сладко снаружи, хитро внутри!',
  'Крути, пока не получится!',
  'Посмотрим, кто ответит первым!',
  'Цвета и числа… идеальный микс!',
  'Держи ритм… не промахнись!',
  'Вопросы сыплются… как дождь!',
  'Все на борт… начинается вызов!',
  'Мягко… но коварно!',
  'Мал, да удал!',
  'Развивай ум вместе со мной!',
  'Я быстр как ветер!',
  'Новый уровень… шаг за шагом!',
  'Крепок как скала!',
  'Сияй и зарабатывай очки!',
  'Сладкий подарок для мозга!',
  'Крути-крути… и отвечай!',
  'Вкусный вызов!',
  'Целься точно… попади!',
  'Идеальный раунд… справишься?',
  'Хрустящий вызов!',
  'Поскользнёшься — если ошибёшься!',
  'Мягко… но непросто!',
  'Сверхсладко, сверхсложно!',
  'Остуди ошибки… думай ясно!',
  'Обработка… успеваешь?',
  'Система готова к игре!',
  'Крути мысли!',
  'Соединяй идеи быстро!',
  'Мал, но быстр!',
  'Включи свой свет!',
  'Загадочный вопрос!',
  'Тап… и попади!',
  'Растягивай ум!',
  'Береги ответы!',
  'Сияй в каждом ответе!',
  'Плыви быстрее… думай умнее!',
  'Впереди огромный вызов!',
  'Пух! Отвечай сейчас!',
  'Вбок… но уверенно!',
  'Плыви по течению!',
  'Не запутайся!',
  'Плыви к ответу!',
  'У меня полно вариантов!',
  'Быстро… очень быстро!',
  'Всё крутится… будь внимателен!',
  'Спокойствие и точность!',
  'Космический уровень!',
  'Быстрый шаг!',
  'Целься высоко!',
  'Сияй во тьме!',
  'Вызовы сыплются!',
  'Это вне земли!',
  'Крути… и отвечай!',
  'Здесь возможно всё!',
  'Найди выход!',
  'Каждая снежинка на счету!',
  'Расти с каждым верным ответом!',
  'Чувствуй ритм!',
  'Обнимательный… но жёсткий!',
  'Подними жару!',
  'Создай ответ!',
  'Пора учиться!',
  'Идеальный рецепт!',
  'Исцели ошибки!',
  'Высоко и быстро!',
  'Жми верное!',
  'Максимальная скорость!',
  'Всё связано!',
  'Игровой режим: ВКЛ!',
  'Собери ответ!',
  'Следующая остановка: верно!',
  'Подпрыгни и ответь!',
  'Соедини идеи!',
  'Плыви… и думай!',
  'Магический вызов!',
  'Чуть-чуть магии!',
  'Легендарный вызов!',
  'Свет и логика!',
  'Верь в себя!',
  'Не заблудись!',
  'Выдержи вызов!',
  'Кристально ясно!',
  'Почувствуй вызов!',
  'Всё возможно!',
  'Спокойная голова — ясные ответы!',
  'Беги и забивай!',
  'Ныряй!',
  'Разбей рекорд!',
  'Лови волну и отвечай!',
  'Покори уровень!',
  'Не останавливайся!',
  'Ускорь мозг!',
  'Прыгай выше!',
  'Нокаут… для ума!',
];
